/*
 * Gearlynx - Lynx Emulator
 * Copyright (C) 2025  Ignacio Sanchez

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses/
 *
 */
#ifndef HUC6280_NAME_H
#define HUC6280_NAME_H

enum GLYNX_OPCode_Type
{
    GLYNX_OPCode_Type_Implied,
    GLYNX_OPCode_Type_1b,
    GLYNX_OPCode_Type_1b_1b,
    GLYNX_OPCode_Type_1b_2b,
    GLYNX_OPCode_Type_2b,
    GLYNX_OPCode_Type_2b_2b_2b,
    GLYNX_OPCode_Type_1b_Relative,
    GLYNX_OPCode_Type_1b_1b_Relative,
};

struct GLYNX_OPCode_Info
{
    const char* name;
    GLYNX_OPCode_Type type;
};

static const GLYNX_OPCode_Info k_m6502_opcode_names[256] = {
    { "BRK", GLYNX_OPCode_Type_Implied },
    { "ORA $(%02X,X)", GLYNX_OPCode_Type_1b },
    { "SXY", GLYNX_OPCode_Type_Implied },
    { "NOP  {}[UNOFFICIAL]", GLYNX_OPCode_Type_Implied },
    { "TSB $%02X", GLYNX_OPCode_Type_1b },
    { "ORA $%02X", GLYNX_OPCode_Type_1b },
    { "ASL $%02X", GLYNX_OPCode_Type_1b },
    { "RMB 0,$%02X", GLYNX_OPCode_Type_1b },
    { "PHP", GLYNX_OPCode_Type_Implied },
    { "ORA #$%02X", GLYNX_OPCode_Type_1b },
    { "ASL A", GLYNX_OPCode_Type_Implied },
    { "NOP  {}[UNOFFICIAL]", GLYNX_OPCode_Type_Implied },
    { "TSB $%04X", GLYNX_OPCode_Type_2b },
    { "ORA $%04X", GLYNX_OPCode_Type_2b },
    { "ASL $%04X", GLYNX_OPCode_Type_2b },
    { "BBR 0,$%02X,$%04X  {}[%+d]", GLYNX_OPCode_Type_1b_1b_Relative },

    { "BPL $%04X  {}[%+d]", GLYNX_OPCode_Type_1b_Relative },
    { "ORA ($%02X),Y", GLYNX_OPCode_Type_1b },
    { "ORA ($%02X)", GLYNX_OPCode_Type_1b },
    { "NOP  {}[UNOFFICIAL]", GLYNX_OPCode_Type_Implied },
    { "TRB $%02X", GLYNX_OPCode_Type_1b },
    { "ORA $%02X,X", GLYNX_OPCode_Type_1b },
    { "ASL $%02X,X", GLYNX_OPCode_Type_1b },
    { "RMB 1,$%02X", GLYNX_OPCode_Type_1b },
    { "CLC", GLYNX_OPCode_Type_Implied },
    { "ORA $%04X,Y", GLYNX_OPCode_Type_2b },
    { "INC A", GLYNX_OPCode_Type_Implied },
    { "NOP  {}[UNOFFICIAL]", GLYNX_OPCode_Type_Implied },
    { "TRB $%04X", GLYNX_OPCode_Type_2b },
    { "ORA $%04X,X", GLYNX_OPCode_Type_2b },
    { "ASL $%04X,X", GLYNX_OPCode_Type_2b },
    { "BBR 1,$%02X,$%04X  {}[%+d]", GLYNX_OPCode_Type_1b_1b_Relative },

    { "JSR $%04X", GLYNX_OPCode_Type_2b },
    { "AND $(%02X,X)", GLYNX_OPCode_Type_1b },
    { "SAX", GLYNX_OPCode_Type_Implied },
    { "NOP  {}[UNOFFICIAL]", GLYNX_OPCode_Type_Implied },
    { "BIT $%02X", GLYNX_OPCode_Type_1b },
    { "AND $%02X", GLYNX_OPCode_Type_1b },
    { "ROL $%02X", GLYNX_OPCode_Type_1b },
    { "RMB 2,$%02X", GLYNX_OPCode_Type_1b },
    { "PLP", GLYNX_OPCode_Type_Implied },
    { "AND #$%02X", GLYNX_OPCode_Type_1b },
    { "ROL A", GLYNX_OPCode_Type_Implied },
    { "NOP  {}[UNOFFICIAL]", GLYNX_OPCode_Type_Implied },
    { "BIT $%04X", GLYNX_OPCode_Type_2b },
    { "AND $%04X", GLYNX_OPCode_Type_2b },
    { "ROL $%04X", GLYNX_OPCode_Type_2b },
    { "BBR 2,$%02X,$%04X  {}[%+d]", GLYNX_OPCode_Type_1b_1b_Relative },

    { "BMI $%04X  {}[%+d]", GLYNX_OPCode_Type_1b_Relative },
    { "AND ($%02X),Y", GLYNX_OPCode_Type_1b },
    { "AND ($%02X)", GLYNX_OPCode_Type_1b },
    { "NOP  {}[UNOFFICIAL]", GLYNX_OPCode_Type_Implied },
    { "BIT $%02X,X", GLYNX_OPCode_Type_1b },
    { "AND $%02X,X", GLYNX_OPCode_Type_1b },
    { "ROL $%02X,X", GLYNX_OPCode_Type_1b },
    { "RMB 3,$%02X", GLYNX_OPCode_Type_1b },
    { "SEC", GLYNX_OPCode_Type_Implied },
    { "AND $%04X,Y", GLYNX_OPCode_Type_2b },
    { "DEC A", GLYNX_OPCode_Type_Implied },
    { "NOP  {}[UNOFFICIAL]", GLYNX_OPCode_Type_Implied },
    { "BIT $%04X,X", GLYNX_OPCode_Type_2b },
    { "AND $%04X,X", GLYNX_OPCode_Type_2b },
    { "ROL $%04X,X", GLYNX_OPCode_Type_2b },
    { "BBR 3,$%02X,$%04X  {}[%+d]", GLYNX_OPCode_Type_1b_1b_Relative },

    { "RTI", GLYNX_OPCode_Type_Implied },
    { "EOR $(%02X,X)", GLYNX_OPCode_Type_1b },
    { "SAY", GLYNX_OPCode_Type_Implied },
    { "TMA #$%02X", GLYNX_OPCode_Type_1b },
    { "BSR $%04X  {}[%+d]", GLYNX_OPCode_Type_1b_Relative },
    { "EOR $%02X", GLYNX_OPCode_Type_1b },
    { "LSR $%02X", GLYNX_OPCode_Type_1b },
    { "RMB 4,$%02X", GLYNX_OPCode_Type_1b },
    { "PHA", GLYNX_OPCode_Type_Implied },
    { "EOR #$%02X", GLYNX_OPCode_Type_1b },
    { "LSR A", GLYNX_OPCode_Type_Implied },
    { "NOP  {}[UNOFFICIAL]", GLYNX_OPCode_Type_Implied },
    { "JMP $%04X", GLYNX_OPCode_Type_2b },
    { "EOR $%04X", GLYNX_OPCode_Type_2b },
    { "LSR $%04X", GLYNX_OPCode_Type_2b },
    { "BBR 4,$%02X,$%04X  {}[%+d]", GLYNX_OPCode_Type_1b_1b_Relative },

    { "BVC $%04X  {}[%+d]", GLYNX_OPCode_Type_1b_Relative },
    { "EOR ($%02X),Y", GLYNX_OPCode_Type_1b },
    { "EOR ($%02X)", GLYNX_OPCode_Type_1b },
    { "TAM #$%02X", GLYNX_OPCode_Type_1b },
    { "CSL", GLYNX_OPCode_Type_Implied },
    { "EOR $%02X,X", GLYNX_OPCode_Type_1b },
    { "LSR $%02X,X", GLYNX_OPCode_Type_1b },
    { "RMB 5,$%02X", GLYNX_OPCode_Type_1b },
    { "CLI", GLYNX_OPCode_Type_Implied },
    { "EOR $%04X,Y", GLYNX_OPCode_Type_2b },
    { "PHY", GLYNX_OPCode_Type_Implied },
    { "NOP  {}[UNOFFICIAL]", GLYNX_OPCode_Type_Implied },
    { "NOP  {}[UNOFFICIAL]", GLYNX_OPCode_Type_Implied },
    { "EOR $%04X,X", GLYNX_OPCode_Type_2b },
    { "LSR $%04X,X", GLYNX_OPCode_Type_2b },
    { "BBR 5,$%02X,$%04X  {}[%+d]", GLYNX_OPCode_Type_1b_1b_Relative },

    { "RTS", GLYNX_OPCode_Type_Implied },
    { "ADC $(%02X,X)", GLYNX_OPCode_Type_1b },
    { "CLA", GLYNX_OPCode_Type_Implied },
    { "NOP  {}[UNOFFICIAL]", GLYNX_OPCode_Type_Implied },
    { "STZ $%02X", GLYNX_OPCode_Type_1b },
    { "ADC $%02X", GLYNX_OPCode_Type_1b },
    { "ROR $%02X", GLYNX_OPCode_Type_1b },
    { "RMB 6,$%02X", GLYNX_OPCode_Type_1b },
    { "PLA", GLYNX_OPCode_Type_Implied },
    { "ADC #$%02X", GLYNX_OPCode_Type_1b },
    { "ROR A", GLYNX_OPCode_Type_Implied },
    { "NOP  {}[UNOFFICIAL]", GLYNX_OPCode_Type_Implied },
    { "JMP ($%04X)", GLYNX_OPCode_Type_2b },
    { "ADC $%04X", GLYNX_OPCode_Type_2b },
    { "ROR $%04X", GLYNX_OPCode_Type_2b },
    { "BBR 6,$%02X,$%04X  {}[%+d]", GLYNX_OPCode_Type_1b_1b_Relative },

    { "BVS $%04X  {}[%+d]", GLYNX_OPCode_Type_1b_Relative },
    { "ADC ($%02X),Y", GLYNX_OPCode_Type_1b },
    { "ADC ($%02X)", GLYNX_OPCode_Type_1b },
    { "TII $%04X,$%04X,$%04X", GLYNX_OPCode_Type_2b_2b_2b },
    { "STZ $%02X,X", GLYNX_OPCode_Type_1b },
    { "ADC $%02X,X", GLYNX_OPCode_Type_1b },
    { "ROR $%02X,X", GLYNX_OPCode_Type_1b },
    { "RMB 7,$%02X", GLYNX_OPCode_Type_1b },
    { "SEI", GLYNX_OPCode_Type_Implied },
    { "ADC $%04X,Y", GLYNX_OPCode_Type_2b },
    { "PLY", GLYNX_OPCode_Type_Implied },
    { "NOP  {}[UNOFFICIAL]", GLYNX_OPCode_Type_Implied },
    { "JMP $(%04X,X)", GLYNX_OPCode_Type_2b },
    { "ADC $%04X,X", GLYNX_OPCode_Type_2b },
    { "ROR $%04X,X", GLYNX_OPCode_Type_2b },
    { "BBR 7,$%02X,$%04X  {}[%+d]", GLYNX_OPCode_Type_1b_1b_Relative },

    { "BRA $%04X  {}[%+d]", GLYNX_OPCode_Type_1b_Relative },
    { "STA $(%02X,X)", GLYNX_OPCode_Type_1b },
    { "CLX", GLYNX_OPCode_Type_Implied },
    { "TST #$%02X,$%02X", GLYNX_OPCode_Type_1b_1b },
    { "STY $%02X", GLYNX_OPCode_Type_1b },
    { "STA $%02X", GLYNX_OPCode_Type_1b },
    { "STX $%02X", GLYNX_OPCode_Type_1b },
    { "SMB 0,$%02X", GLYNX_OPCode_Type_1b },
    { "DEY", GLYNX_OPCode_Type_Implied },
    { "BIT #$%02X", GLYNX_OPCode_Type_1b },
    { "TXA", GLYNX_OPCode_Type_Implied },
    { "NOP  {}[UNOFFICIAL]", GLYNX_OPCode_Type_Implied },
    { "STY $%04X", GLYNX_OPCode_Type_2b },
    { "STA $%04X", GLYNX_OPCode_Type_2b },
    { "STX $%04X", GLYNX_OPCode_Type_2b },
    { "BBS 0,$%02X,$%04X  {}[%+d]", GLYNX_OPCode_Type_1b_1b_Relative },

    { "BCC $%04X  {}[%+d]", GLYNX_OPCode_Type_1b_Relative },
    { "STA ($%02X),Y", GLYNX_OPCode_Type_1b },
    { "STA ($%02X)", GLYNX_OPCode_Type_1b },
    { "TST #$%02X,$%04X", GLYNX_OPCode_Type_1b_2b },
    { "STY $%02X,X", GLYNX_OPCode_Type_1b },
    { "STA $%02X,X", GLYNX_OPCode_Type_1b },
    { "STX $%02X,Y", GLYNX_OPCode_Type_1b },
    { "SMB 1,$%02X", GLYNX_OPCode_Type_1b },
    { "TYA", GLYNX_OPCode_Type_Implied },
    { "STA $%04X,Y", GLYNX_OPCode_Type_2b },
    { "TXS", GLYNX_OPCode_Type_Implied },
    { "NOP  {}[UNOFFICIAL]", GLYNX_OPCode_Type_Implied },
    { "STZ $%04X", GLYNX_OPCode_Type_2b },
    { "STA $%04X,X", GLYNX_OPCode_Type_2b },
    { "STZ $%04X,X", GLYNX_OPCode_Type_2b },
    { "BBS 1,$%02X,$%04X  {}[%+d]", GLYNX_OPCode_Type_1b_1b_Relative },

    { "LDY #$%02X", GLYNX_OPCode_Type_1b },
    { "LDA $(%02X,X)", GLYNX_OPCode_Type_1b },
    { "LDX #$%02X", GLYNX_OPCode_Type_1b },
    { "TST #$%02X,$%02X,X", GLYNX_OPCode_Type_1b_1b },
    { "LDY $%02X", GLYNX_OPCode_Type_1b },
    { "LDA $%02X", GLYNX_OPCode_Type_1b },
    { "LDX $%02X", GLYNX_OPCode_Type_1b },
    { "SMB 2,$%02X", GLYNX_OPCode_Type_1b },
    { "TAY", GLYNX_OPCode_Type_Implied },
    { "LDA #$%02X", GLYNX_OPCode_Type_1b },
    { "TAX", GLYNX_OPCode_Type_Implied },
    { "NOP  {}[UNOFFICIAL]", GLYNX_OPCode_Type_Implied },
    { "LDY $%04X", GLYNX_OPCode_Type_2b },
    { "LDA $%04X", GLYNX_OPCode_Type_2b },
    { "LDX $%04X", GLYNX_OPCode_Type_2b },
    { "BBS 2,$%02X,$%04X  {}[%+d]", GLYNX_OPCode_Type_1b_1b_Relative },

    { "BCS $%04X  {}[%+d]", GLYNX_OPCode_Type_1b_Relative },
    { "LDA ($%02X),Y", GLYNX_OPCode_Type_1b },
    { "LDA ($%02X)", GLYNX_OPCode_Type_1b },
    { "TST #$%02X,$%04X,X", GLYNX_OPCode_Type_1b_2b },
    { "LDY $%02X,X", GLYNX_OPCode_Type_1b },
    { "LDA $%02X,X", GLYNX_OPCode_Type_1b },
    { "LDX $%02X,Y", GLYNX_OPCode_Type_1b },
    { "SMB 3,$%02X", GLYNX_OPCode_Type_1b },
    { "CLV", GLYNX_OPCode_Type_Implied },
    { "LDA $%04X,Y", GLYNX_OPCode_Type_2b },
    { "TSX", GLYNX_OPCode_Type_Implied },
    { "NOP  {}[UNOFFICIAL]", GLYNX_OPCode_Type_Implied },
    { "LDY $%04X,X", GLYNX_OPCode_Type_2b },
    { "LDA $%04X,X", GLYNX_OPCode_Type_2b },
    { "LDX $%04X,Y", GLYNX_OPCode_Type_2b },
    { "BBS 3,$%02X,$%04X  {}[%+d]", GLYNX_OPCode_Type_1b_1b_Relative },

    { "CPY #$%02X", GLYNX_OPCode_Type_1b },
    { "CMP $(%02X,X)", GLYNX_OPCode_Type_1b },
    { "CLY", GLYNX_OPCode_Type_Implied },
    { "TDD $%04X,$%04X,$%04X", GLYNX_OPCode_Type_2b_2b_2b },
    { "CPY $%02X", GLYNX_OPCode_Type_1b },
    { "CMP $%02X", GLYNX_OPCode_Type_1b },
    { "DEC $%02X", GLYNX_OPCode_Type_1b },
    { "SMB 4,$%02X", GLYNX_OPCode_Type_1b },
    { "INY", GLYNX_OPCode_Type_Implied },
    { "CMP #$%02X", GLYNX_OPCode_Type_1b },
    { "DEX", GLYNX_OPCode_Type_Implied },
    { "NOP  {}[UNOFFICIAL WAI]", GLYNX_OPCode_Type_Implied },
    { "CPY $%04X", GLYNX_OPCode_Type_2b },
    { "CMP $%04X", GLYNX_OPCode_Type_2b },
    { "DEC $%04X", GLYNX_OPCode_Type_2b },
    { "BBS 4,$%02X,$%04X  {}[%+d]", GLYNX_OPCode_Type_1b_1b_Relative },

    { "BNE $%04X  {}[%+d]", GLYNX_OPCode_Type_1b_Relative },
    { "CMP ($%02X),Y", GLYNX_OPCode_Type_1b },
    { "CMP ($%02X)", GLYNX_OPCode_Type_1b },
    { "TIN $%04X,$%04X,$%04X", GLYNX_OPCode_Type_2b_2b_2b },
    { "CSH", GLYNX_OPCode_Type_Implied },
    { "CMP $%02X,X", GLYNX_OPCode_Type_1b },
    { "DEC $%02X,X", GLYNX_OPCode_Type_1b },
    { "SMB 5,$%02X", GLYNX_OPCode_Type_1b },
    { "CLD", GLYNX_OPCode_Type_Implied },
    { "CMP $%04X,Y", GLYNX_OPCode_Type_2b },
    { "PHX", GLYNX_OPCode_Type_Implied },
    { "NOP  {}[UNOFFICIAL]", GLYNX_OPCode_Type_Implied },
    { "NOP  {}[UNOFFICIAL]", GLYNX_OPCode_Type_Implied },
    { "CMP $%04X,X", GLYNX_OPCode_Type_2b },
    { "DEC $%04X,X", GLYNX_OPCode_Type_2b },
    { "BBS 5,$%02X,$%04X  {}[%+d]", GLYNX_OPCode_Type_1b_1b_Relative },

    { "CPX #$%02X", GLYNX_OPCode_Type_1b },
    { "SBC $(%02X,X)", GLYNX_OPCode_Type_1b },
    { "NOP  {}[UNOFFICIAL]", GLYNX_OPCode_Type_Implied },
    { "TIA $%04X,$%04X,$%04X", GLYNX_OPCode_Type_2b_2b_2b },
    { "CPX $%02X", GLYNX_OPCode_Type_1b },
    { "SBC $%02X", GLYNX_OPCode_Type_1b },
    { "INC $%02X", GLYNX_OPCode_Type_1b },
    { "SMB 6,$%02X", GLYNX_OPCode_Type_1b },
    { "INX", GLYNX_OPCode_Type_Implied },
    { "SBC #$%02X", GLYNX_OPCode_Type_1b },
    { "NOP", GLYNX_OPCode_Type_Implied },
    { "NOP  {}[UNOFFICIAL]", GLYNX_OPCode_Type_Implied },
    { "CPX $%04X", GLYNX_OPCode_Type_2b },
    { "SBC $%04X", GLYNX_OPCode_Type_2b },
    { "INC $%04X", GLYNX_OPCode_Type_2b },
    { "BBS 6,$%02X,$%04X  {}[%+d]", GLYNX_OPCode_Type_1b_1b_Relative },

    { "BEQ $%04X  {}[%+d]", GLYNX_OPCode_Type_1b_Relative },
    { "SBC ($%02X),Y", GLYNX_OPCode_Type_1b },
    { "SBC ($%02X)", GLYNX_OPCode_Type_1b },
    { "TAI $%04X,$%04X,$%04X", GLYNX_OPCode_Type_2b_2b_2b },
    { "SET", GLYNX_OPCode_Type_Implied },
    { "SBC $%02X,X", GLYNX_OPCode_Type_1b },
    { "INC $%02X,X", GLYNX_OPCode_Type_1b },
    { "SMB 7,$%02X", GLYNX_OPCode_Type_1b },
    { "SED", GLYNX_OPCode_Type_Implied },
    { "SBC $%04X,Y", GLYNX_OPCode_Type_2b },
    { "PLX", GLYNX_OPCode_Type_Implied },
    { "NOP  {}[UNOFFICIAL]", GLYNX_OPCode_Type_Implied },
    { "NOP  {}[UNOFFICIAL]", GLYNX_OPCode_Type_Implied },
    { "SBC $%04X,X", GLYNX_OPCode_Type_2b },
    { "INC $%04X,X", GLYNX_OPCode_Type_2b },
    { "BBS 7,$%02X,$%04X  {}[%+d]", GLYNX_OPCode_Type_1b_1b_Relative }
};

#endif /* HUC6280_NAME_H */